[package]
name = "virtual_gamepad"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.47.1", features = ["full"]}
tokio-tungstenite = "0.27.0"
regex = "1"
futures-util = "0.3.31"
serde_json = "1.0.145"
serde = { version = "1.0", features = ["derive"] }
vigem-client = "0.1.4"

